// default package
// Generated 16-May-2012 11:53:05 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 *  generated by hbm2java
 */
public class   implements java.io.Serializable {


     private String providerId;
     private String providerName;
     private String inProcess;
     private String providerType;
     private String alsoKnownAs;
     private String address1;
     private String address2;
     private String towncity;
     private String county;
     private String postcode;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String typeInfo1;
     private String typeInfo2;
     private String underReviewText;
     private String telephone;
     private String email;
     private String website;
     private String fax;
     private String isPartnership;
     private String hashvalue;
     private Character action;

    public () {
    }

	
    public (String providerId) {
        this.providerId = providerId;
    }
    public (String providerId, String providerName, String inProcess, String providerType, String alsoKnownAs, String address1, String address2, String towncity, String county, String postcode, BigDecimal latitude, BigDecimal longitude, String typeInfo1, String typeInfo2, String underReviewText, String telephone, String email, String website, String fax, String isPartnership, String hashvalue, Character action) {
       this.providerId = providerId;
       this.providerName = providerName;
       this.inProcess = inProcess;
       this.providerType = providerType;
       this.alsoKnownAs = alsoKnownAs;
       this.address1 = address1;
       this.address2 = address2;
       this.towncity = towncity;
       this.county = county;
       this.postcode = postcode;
       this.latitude = latitude;
       this.longitude = longitude;
       this.typeInfo1 = typeInfo1;
       this.typeInfo2 = typeInfo2;
       this.underReviewText = underReviewText;
       this.telephone = telephone;
       this.email = email;
       this.website = website;
       this.fax = fax;
       this.isPartnership = isPartnership;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }
    public String getInProcess() {
        return this.inProcess;
    }
    
    public void setInProcess(String inProcess) {
        this.inProcess = inProcess;
    }
    public String getProviderType() {
        return this.providerType;
    }
    
    public void setProviderType(String providerType) {
        this.providerType = providerType;
    }
    public String getAlsoKnownAs() {
        return this.alsoKnownAs;
    }
    
    public void setAlsoKnownAs(String alsoKnownAs) {
        this.alsoKnownAs = alsoKnownAs;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getTowncity() {
        return this.towncity;
    }
    
    public void setTowncity(String towncity) {
        this.towncity = towncity;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public String getTypeInfo1() {
        return this.typeInfo1;
    }
    
    public void setTypeInfo1(String typeInfo1) {
        this.typeInfo1 = typeInfo1;
    }
    public String getTypeInfo2() {
        return this.typeInfo2;
    }
    
    public void setTypeInfo2(String typeInfo2) {
        this.typeInfo2 = typeInfo2;
    }
    public String getUnderReviewText() {
        return this.underReviewText;
    }
    
    public void setUnderReviewText(String underReviewText) {
        this.underReviewText = underReviewText;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getIsPartnership() {
        return this.isPartnership;
    }
    
    public void setIsPartnership(String isPartnership) {
        this.isPartnership = isPartnership;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


