package org.cqc.etl.factories.pptest2;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import org.cqc.etl.model.dao.pptest2.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernatePptest2DaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernatePptest2DaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernatePptest2DaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernatePptest2DaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a ChapterDao instance.
	 * 
	 * @return a ChapterDao instance
	 */
	public static ChapterDao getChapterDao() {
		return (ChapterDao) getBean("chapterDaoImpl"); 
	}
	/**
	 * Returns a LocationDao instance.
	 * 
	 * @return a LocationDao instance
	 */
	public static LocationDao getLocationDao() {
		return (LocationDao) getBean("locationDaoImpl"); 
	}
	/**
	 * Returns a LocationConditionDao instance.
	 * 
	 * @return a LocationConditionDao instance
	 */
	public static LocationConditionDao getLocationConditionDao() {
		return (LocationConditionDao) getBean("locationConditionDaoImpl"); 
	}
	/**
	 * Returns a LocationRegulatedActivityDao instance.
	 * 
	 * @return a LocationRegulatedActivityDao instance
	 */
	public static LocationRegulatedActivityDao getLocationRegulatedActivityDao() {
		return (LocationRegulatedActivityDao) getBean("locationRegulatedActivityDaoImpl"); 
	}
	/**
	 * Returns a NominatedIndividualDao instance.
	 * 
	 * @return a NominatedIndividualDao instance
	 */
	public static NominatedIndividualDao getNominatedIndividualDao() {
		return (NominatedIndividualDao) getBean("nominatedIndividualDaoImpl"); 
	}
	/**
	 * Returns a OutcomeDao instance.
	 * 
	 * @return a OutcomeDao instance
	 */
	public static OutcomeDao getOutcomeDao() {
		return (OutcomeDao) getBean("outcomeDaoImpl"); 
	}
	/**
	 * Returns a PartnerDao instance.
	 * 
	 * @return a PartnerDao instance
	 */
	public static PartnerDao getPartnerDao() {
		return (PartnerDao) getBean("partnerDaoImpl"); 
	}
	/**
	 * Returns a ProviderDao instance.
	 * 
	 * @return a ProviderDao instance
	 */
	public static ProviderDao getProviderDao() {
		return (ProviderDao) getBean("providerDaoImpl"); 
	}
	/**
	 * Returns a ProviderConditionDao instance.
	 * 
	 * @return a ProviderConditionDao instance
	 */
	public static ProviderConditionDao getProviderConditionDao() {
		return (ProviderConditionDao) getBean("providerConditionDaoImpl"); 
	}
	/**
	 * Returns a ProviderRegulatedActivityDao instance.
	 * 
	 * @return a ProviderRegulatedActivityDao instance
	 */
	public static ProviderRegulatedActivityDao getProviderRegulatedActivityDao() {
		return (ProviderRegulatedActivityDao) getBean("providerRegulatedActivityDaoImpl"); 
	}
	/**
	 * Returns a RegisteredManagerDao instance.
	 * 
	 * @return a RegisteredManagerDao instance
	 */
	public static RegisteredManagerDao getRegisteredManagerDao() {
		return (RegisteredManagerDao) getBean("registeredManagerDaoImpl"); 
	}
	/**
	 * Returns a RegisteredManagerConditionDao instance.
	 * 
	 * @return a RegisteredManagerConditionDao instance
	 */
	public static RegisteredManagerConditionDao getRegisteredManagerConditionDao() {
		return (RegisteredManagerConditionDao) getBean("registeredManagerConditionDaoImpl"); 
	}
	/**
	 * Returns a ReportSummaryDao instance.
	 * 
	 * @return a ReportSummaryDao instance
	 */
	public static ReportSummaryDao getReportSummaryDao() {
		return (ReportSummaryDao) getBean("reportSummaryDaoImpl"); 
	}
	/**
	 * Returns a ServiceTypeDao instance.
	 * 
	 * @return a ServiceTypeDao instance
	 */
	public static ServiceTypeDao getServiceTypeDao() {
		return (ServiceTypeDao) getBean("serviceTypeDaoImpl"); 
	}
	/**
	 * Returns a ServiceUserBandDao instance.
	 * 
	 * @return a ServiceUserBandDao instance
	 */
	public static ServiceUserBandDao getServiceUserBandDao() {
		return (ServiceUserBandDao) getBean("serviceUserBandDaoImpl"); 
	}

}
