package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Chapter generated by hbm2java
 */
public class Chapter  implements java.io.Serializable {


     private ChapterId id;
     private Integer score;
     private Character actionCode;
     private Date lastUpdated;

    public Chapter() {
    }

	
    public Chapter(ChapterId id) {
        this.id = id;
    }
    public Chapter(ChapterId id, Integer score, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.score = score;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public ChapterId getId() {
        return this.id;
    }
    
    public void setId(ChapterId id) {
        this.id = id;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


