package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * LocationRegulatedActivity generated by hbm2java
 */
public class LocationRegulatedActivity  implements java.io.Serializable {


     private LocationRegulatedActivityId id;
     private Character actionCode;
     private Date lastUpdated;

    public LocationRegulatedActivity() {
    }

	
    public LocationRegulatedActivity(LocationRegulatedActivityId id) {
        this.id = id;
    }
    public LocationRegulatedActivity(LocationRegulatedActivityId id, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public LocationRegulatedActivityId getId() {
        return this.id;
    }
    
    public void setId(LocationRegulatedActivityId id) {
        this.id = id;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


