package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private LocationId id;
     private String name;
     private String inProcess;
     private String type;
     private String alsoKnownAs;
     private String address1;
     private String address2;
     private String towncity;
     private String county;
     private String postcode;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private String subtype;
     private String telephone;
     private String email;
     private String website;
     private String fax;
     private String underReviewText;
     private String userExperience;
     private String aboutLocation;
     private Character actionCode;
     private Date lastUpdated;

    public Location() {
    }

	
    public Location(LocationId id) {
        this.id = id;
    }
    public Location(LocationId id, String name, String inProcess, String type, String alsoKnownAs, String address1, String address2, String towncity, String county, String postcode, BigDecimal latitude, BigDecimal longitude, String subtype, String telephone, String email, String website, String fax, String underReviewText, String userExperience, String aboutLocation, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.name = name;
       this.inProcess = inProcess;
       this.type = type;
       this.alsoKnownAs = alsoKnownAs;
       this.address1 = address1;
       this.address2 = address2;
       this.towncity = towncity;
       this.county = county;
       this.postcode = postcode;
       this.latitude = latitude;
       this.longitude = longitude;
       this.subtype = subtype;
       this.telephone = telephone;
       this.email = email;
       this.website = website;
       this.fax = fax;
       this.underReviewText = underReviewText;
       this.userExperience = userExperience;
       this.aboutLocation = aboutLocation;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public LocationId getId() {
        return this.id;
    }
    
    public void setId(LocationId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInProcess() {
        return this.inProcess;
    }
    
    public void setInProcess(String inProcess) {
        this.inProcess = inProcess;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAlsoKnownAs() {
        return this.alsoKnownAs;
    }
    
    public void setAlsoKnownAs(String alsoKnownAs) {
        this.alsoKnownAs = alsoKnownAs;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getTowncity() {
        return this.towncity;
    }
    
    public void setTowncity(String towncity) {
        this.towncity = towncity;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public String getSubtype() {
        return this.subtype;
    }
    
    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getUnderReviewText() {
        return this.underReviewText;
    }
    
    public void setUnderReviewText(String underReviewText) {
        this.underReviewText = underReviewText;
    }
    public String getUserExperience() {
        return this.userExperience;
    }
    
    public void setUserExperience(String userExperience) {
        this.userExperience = userExperience;
    }
    public String getAboutLocation() {
        return this.aboutLocation;
    }
    
    public void setAboutLocation(String aboutLocation) {
        this.aboutLocation = aboutLocation;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


