package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA



/**
 * Lookup generated by hbm2java
 */
public class Lookup  implements java.io.Serializable {


     private LookupId id;

    public Lookup() {
    }

    public Lookup(LookupId id) {
       this.id = id;
    }
   
    public LookupId getId() {
        return this.id;
    }
    
    public void setId(LookupId id) {
        this.id = id;
    }




}


