package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA



/**
 * PartnerId generated by hbm2java
 */
public class PartnerId  implements java.io.Serializable {


     private String providerId;
     private String partnerId;

    public PartnerId() {
    }

    public PartnerId(String providerId, String partnerId) {
       this.providerId = providerId;
       this.partnerId = partnerId;
    }
   
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartnerId) ) return false;
		 PartnerId castOther = ( PartnerId ) other; 
         
		 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getPartnerId()==castOther.getPartnerId()) || ( this.getPartnerId()!=null && castOther.getPartnerId()!=null && this.getPartnerId().equals(castOther.getPartnerId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getPartnerId() == null ? 0 : this.getPartnerId().hashCode() );
         return result;
   }   


}


