package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * ProviderCondition generated by hbm2java
 */
public class ProviderCondition  implements java.io.Serializable {


     private ProviderConditionId id;
     private String regulatedActivityNumber;
     private String text;
     private String reason;
     private Character actionCode;
     private Date lastUpdated;

    public ProviderCondition() {
    }

	
    public ProviderCondition(ProviderConditionId id, String regulatedActivityNumber) {
        this.id = id;
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
    public ProviderCondition(ProviderConditionId id, String regulatedActivityNumber, String text, String reason, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.regulatedActivityNumber = regulatedActivityNumber;
       this.text = text;
       this.reason = reason;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public ProviderConditionId getId() {
        return this.id;
    }
    
    public void setId(ProviderConditionId id) {
        this.id = id;
    }
    public String getRegulatedActivityNumber() {
        return this.regulatedActivityNumber;
    }
    
    public void setRegulatedActivityNumber(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


