package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * RegisteredManager generated by hbm2java
 */
public class RegisteredManager  implements java.io.Serializable {


     private RegisteredManagerId id;
     private String name;
     private String managerCondition;
     private Character actionCode;
     private Date lastUpdated;

    public RegisteredManager() {
    }

	
    public RegisteredManager(RegisteredManagerId id) {
        this.id = id;
    }
    public RegisteredManager(RegisteredManagerId id, String name, String managerCondition, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.name = name;
       this.managerCondition = managerCondition;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public RegisteredManagerId getId() {
        return this.id;
    }
    
    public void setId(RegisteredManagerId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getManagerCondition() {
        return this.managerCondition;
    }
    
    public void setManagerCondition(String managerCondition) {
        this.managerCondition = managerCondition;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


