package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * RegisteredManagerCondition generated by hbm2java
 */
public class RegisteredManagerCondition  implements java.io.Serializable {


     private RegisteredManagerConditionId id;
     private String conditionId;
     private String conditionText;
     private Character actionCode;
     private Date lastUpdated;

    public RegisteredManagerCondition() {
    }

	
    public RegisteredManagerCondition(RegisteredManagerConditionId id) {
        this.id = id;
    }
    public RegisteredManagerCondition(RegisteredManagerConditionId id, String conditionId, String conditionText, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.conditionId = conditionId;
       this.conditionText = conditionText;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public RegisteredManagerConditionId getId() {
        return this.id;
    }
    
    public void setId(RegisteredManagerConditionId id) {
        this.id = id;
    }
    public String getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }
    public String getConditionText() {
        return this.conditionText;
    }
    
    public void setConditionText(String conditionText) {
        this.conditionText = conditionText;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


