package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA



/**
 * ReportSummaryId generated by hbm2java
 */
public class ReportSummaryId  implements java.io.Serializable {


     private String providerId;
     private String locationId;

    public ReportSummaryId() {
    }

    public ReportSummaryId(String providerId, String locationId) {
       this.providerId = providerId;
       this.locationId = locationId;
    }
   
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReportSummaryId) ) return false;
		 ReportSummaryId castOther = ( ReportSummaryId ) other; 
         
		 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         return result;
   }   


}


