package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * ServiceUserBand generated by hbm2java
 */
public class ServiceUserBand  implements java.io.Serializable {


     private ServiceUserBandId id;
     private Character actionCode;
     private Date lastUpdated;

    public ServiceUserBand() {
    }

	
    public ServiceUserBand(ServiceUserBandId id) {
        this.id = id;
    }
    public ServiceUserBand(ServiceUserBandId id, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public ServiceUserBandId getId() {
        return this.id;
    }
    
    public void setId(ServiceUserBandId id) {
        this.id = id;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


