package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.Chapter;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ChapterDao;
import org.cqc.etl.model.obj.pptest2.ChapterPK;
 
/**
 * DAO for table: Chapter.
 * @author autogenerated
 */
@Repository
public class ChapterDaoImpl extends GenericHibernateDaoImpl<Chapter, ChapterPK> implements ChapterDao {
	
	/** Constructor method. */
		public ChapterDaoImpl() {
			super(Chapter.class);
		}
	}

