package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.LocationConditionPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationConditionPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: LocationConditionPK.
 * @author autogenerated
 */
@Repository
public class LocationConditionPKDaoImpl extends GenericHibernateDaoImpl<LocationConditionPK, Serializable> implements LocationConditionPKDao {
	
	/** Constructor method. */
		public LocationConditionPKDaoImpl() {
			super(LocationConditionPK.class);
		}
	}

