package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivityPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationRegulatedActivityPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: LocationRegulatedActivityPK.
 * @author autogenerated
 */
@Repository
public class LocationRegulatedActivityPKDaoImpl extends GenericHibernateDaoImpl<LocationRegulatedActivityPK, Serializable> implements LocationRegulatedActivityPKDao {
	
	/** Constructor method. */
		public LocationRegulatedActivityPKDaoImpl() {
			super(LocationRegulatedActivityPK.class);
		}
	}

