package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.Location;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationDao;
import org.cqc.etl.model.obj.pptest2.LocationPK;
 
/**
 * DAO for table: Location.
 * @author autogenerated
 */
@Repository
public class LocationDaoImpl extends GenericHibernateDaoImpl<Location, LocationPK> implements LocationDao {
	
	/** Constructor method. */
		public LocationDaoImpl() {
			super(Location.class);
		}
	}

