package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivity;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationRegulatedActivityDao;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivityPK;
 
/**
 * DAO for table: LocationRegulatedActivity.
 * @author autogenerated
 */
@Repository
public class LocationRegulatedActivityDaoImpl extends GenericHibernateDaoImpl<LocationRegulatedActivity, LocationRegulatedActivityPK> implements LocationRegulatedActivityDao {
	
	/** Constructor method. */
		public LocationRegulatedActivityDaoImpl() {
			super(LocationRegulatedActivity.class);
		}
	}

