package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.LocationPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: LocationPK.
 * @author autogenerated
 */
@Repository
public class LocationPKDaoImpl extends GenericHibernateDaoImpl<LocationPK, Serializable> implements LocationPKDao {
	
	/** Constructor method. */
		public LocationPKDaoImpl() {
			super(LocationPK.class);
		}
	}

