package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.LocationCondition;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.LocationConditionDao;
import org.cqc.etl.model.obj.pptest2.LocationConditionPK;
 
/**
 * DAO for table: LocationCondition.
 * @author autogenerated
 */
@Repository
public class LocationConditionDaoImpl extends GenericHibernateDaoImpl<LocationCondition, LocationConditionPK> implements LocationConditionDao {
	
	/** Constructor method. */
		public LocationConditionDaoImpl() {
			super(LocationCondition.class);
		}
	}

