package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.NominatedIndividual;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.NominatedIndividualDao;
import org.cqc.etl.model.obj.pptest2.NominatedIndividualPK;
 
/**
 * DAO for table: NominatedIndividual.
 * @author autogenerated
 */
@Repository
public class NominatedIndividualDaoImpl extends GenericHibernateDaoImpl<NominatedIndividual, NominatedIndividualPK> implements NominatedIndividualDao {
	
	/** Constructor method. */
		public NominatedIndividualDaoImpl() {
			super(NominatedIndividual.class);
		}
	}

