package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.OutcomePK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.OutcomePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: OutcomePK.
 * @author autogenerated
 */
@Repository
public class OutcomePKDaoImpl extends GenericHibernateDaoImpl<OutcomePK, Serializable> implements OutcomePKDao {
	
	/** Constructor method. */
		public OutcomePKDaoImpl() {
			super(OutcomePK.class);
		}
	}

