package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.PartnerPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.PartnerPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: PartnerPK.
 * @author autogenerated
 */
@Repository
public class PartnerPKDaoImpl extends GenericHibernateDaoImpl<PartnerPK, Serializable> implements PartnerPKDao {
	
	/** Constructor method. */
		public PartnerPKDaoImpl() {
			super(PartnerPK.class);
		}
	}

