package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.Partner;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.PartnerDao;
import org.cqc.etl.model.obj.pptest2.PartnerPK;
 
/**
 * DAO for table: Partner.
 * @author autogenerated
 */
@Repository
public class PartnerDaoImpl extends GenericHibernateDaoImpl<Partner, PartnerPK> implements PartnerDao {
	
	/** Constructor method. */
		public PartnerDaoImpl() {
			super(Partner.class);
		}
	}

