package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivity;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ProviderRegulatedActivityDao;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivityPK;
 
/**
 * DAO for table: ProviderRegulatedActivity.
 * @author autogenerated
 */
@Repository
public class ProviderRegulatedActivityDaoImpl extends GenericHibernateDaoImpl<ProviderRegulatedActivity, ProviderRegulatedActivityPK> implements ProviderRegulatedActivityDao {
	
	/** Constructor method. */
		public ProviderRegulatedActivityDaoImpl() {
			super(ProviderRegulatedActivity.class);
		}
	}

