package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivityPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ProviderRegulatedActivityPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ProviderRegulatedActivityPK.
 * @author autogenerated
 */
@Repository
public class ProviderRegulatedActivityPKDaoImpl extends GenericHibernateDaoImpl<ProviderRegulatedActivityPK, Serializable> implements ProviderRegulatedActivityPKDao {
	
	/** Constructor method. */
		public ProviderRegulatedActivityPKDaoImpl() {
			super(ProviderRegulatedActivityPK.class);
		}
	}

