package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ProviderCondition;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ProviderConditionDao;
import org.cqc.etl.model.obj.pptest2.ProviderConditionPK;
 
/**
 * DAO for table: ProviderCondition.
 * @author autogenerated
 */
@Repository
public class ProviderConditionDaoImpl extends GenericHibernateDaoImpl<ProviderCondition, ProviderConditionPK> implements ProviderConditionDao {
	
	/** Constructor method. */
		public ProviderConditionDaoImpl() {
			super(ProviderCondition.class);
		}
	}

