package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ProviderConditionPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ProviderConditionPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ProviderConditionPK.
 * @author autogenerated
 */
@Repository
public class ProviderConditionPKDaoImpl extends GenericHibernateDaoImpl<ProviderConditionPK, Serializable> implements ProviderConditionPKDao {
	
	/** Constructor method. */
		public ProviderConditionPKDaoImpl() {
			super(ProviderConditionPK.class);
		}
	}

