package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.RegisteredManager;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.RegisteredManagerDao;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerPK;
 
/**
 * DAO for table: RegisteredManager.
 * @author autogenerated
 */
@Repository
public class RegisteredManagerDaoImpl extends GenericHibernateDaoImpl<RegisteredManager, RegisteredManagerPK> implements RegisteredManagerDao {
	
	/** Constructor method. */
		public RegisteredManagerDaoImpl() {
			super(RegisteredManager.class);
		}
	}

