package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerConditionPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.RegisteredManagerConditionPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: RegisteredManagerConditionPK.
 * @author autogenerated
 */
@Repository
public class RegisteredManagerConditionPKDaoImpl extends GenericHibernateDaoImpl<RegisteredManagerConditionPK, Serializable> implements RegisteredManagerConditionPKDao {
	
	/** Constructor method. */
		public RegisteredManagerConditionPKDaoImpl() {
			super(RegisteredManagerConditionPK.class);
		}
	}

