package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerCondition;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.RegisteredManagerConditionDao;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerConditionPK;
 
/**
 * DAO for table: RegisteredManagerCondition.
 * @author autogenerated
 */
@Repository
public class RegisteredManagerConditionDaoImpl extends GenericHibernateDaoImpl<RegisteredManagerCondition, RegisteredManagerConditionPK> implements RegisteredManagerConditionDao {
	
	/** Constructor method. */
		public RegisteredManagerConditionDaoImpl() {
			super(RegisteredManagerCondition.class);
		}
	}

