package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.RegisteredManagerPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: RegisteredManagerPK.
 * @author autogenerated
 */
@Repository
public class RegisteredManagerPKDaoImpl extends GenericHibernateDaoImpl<RegisteredManagerPK, Serializable> implements RegisteredManagerPKDao {
	
	/** Constructor method. */
		public RegisteredManagerPKDaoImpl() {
			super(RegisteredManagerPK.class);
		}
	}

