package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ReportSummaryPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ReportSummaryPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ReportSummaryPK.
 * @author autogenerated
 */
@Repository
public class ReportSummaryPKDaoImpl extends GenericHibernateDaoImpl<ReportSummaryPK, Serializable> implements ReportSummaryPKDao {
	
	/** Constructor method. */
		public ReportSummaryPKDaoImpl() {
			super(ReportSummaryPK.class);
		}
	}

