package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ReportSummary;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ReportSummaryDao;
import org.cqc.etl.model.obj.pptest2.ReportSummaryPK;
 
/**
 * DAO for table: ReportSummary.
 * @author autogenerated
 */
@Repository
public class ReportSummaryDaoImpl extends GenericHibernateDaoImpl<ReportSummary, ReportSummaryPK> implements ReportSummaryDao {
	
	/** Constructor method. */
		public ReportSummaryDaoImpl() {
			super(ReportSummary.class);
		}
	}

