package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ServiceType;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ServiceTypeDao;
import org.cqc.etl.model.obj.pptest2.ServiceTypePK;
 
/**
 * DAO for table: ServiceType.
 * @author autogenerated
 */
@Repository
public class ServiceTypeDaoImpl extends GenericHibernateDaoImpl<ServiceType, ServiceTypePK> implements ServiceTypeDao {
	
	/** Constructor method. */
		public ServiceTypeDaoImpl() {
			super(ServiceType.class);
		}
	}

