package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ServiceUserBand;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ServiceUserBandDao;
import org.cqc.etl.model.obj.pptest2.ServiceUserBandPK;
 
/**
 * DAO for table: ServiceUserBand.
 * @author autogenerated
 */
@Repository
public class ServiceUserBandDaoImpl extends GenericHibernateDaoImpl<ServiceUserBand, ServiceUserBandPK> implements ServiceUserBandDao {
	
	/** Constructor method. */
		public ServiceUserBandDaoImpl() {
			super(ServiceUserBand.class);
		}
	}

