package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ServiceTypePK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ServiceTypePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ServiceTypePK.
 * @author autogenerated
 */
@Repository
public class ServiceTypePKDaoImpl extends GenericHibernateDaoImpl<ServiceTypePK, Serializable> implements ServiceTypePKDao {
	
	/** Constructor method. */
		public ServiceTypePKDaoImpl() {
			super(ServiceTypePK.class);
		}
	}

