package org.cqc.etl.model.dao.pptest2.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.cqc.etl.model.obj.pptest2.ServiceUserBandPK;
import org.springframework.stereotype.Repository;
import org.cqc.etl.model.dao.pptest2.ServiceUserBandPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ServiceUserBandPK.
 * @author autogenerated
 */
@Repository
public class ServiceUserBandPKDaoImpl extends GenericHibernateDaoImpl<ServiceUserBandPK, Serializable> implements ServiceUserBandPKDao {
	
	/** Constructor method. */
		public ServiceUserBandPKDaoImpl() {
			super(ServiceUserBandPK.class);
		}
	}

