package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * Chapter generated by hbm2java
 */
public class Chapter  implements java.io.Serializable {


     private ChapterId id;
     private Integer chapterScore;
     private String hashvalue;
     private Character action;

    public Chapter() {
    }

	
    public Chapter(ChapterId id) {
        this.id = id;
    }
    public Chapter(ChapterId id, Integer chapterScore, String hashvalue, Character action) {
       this.id = id;
       this.chapterScore = chapterScore;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public ChapterId getId() {
        return this.id;
    }
    
    public void setId(ChapterId id) {
        this.id = id;
    }
    public Integer getChapterScore() {
        return this.chapterScore;
    }
    
    public void setChapterScore(Integer chapterScore) {
        this.chapterScore = chapterScore;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


