package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * ChapterId generated by hbm2java
 */
public class ChapterId  implements java.io.Serializable {


     private String providerId;
     private String locationId;
     private String chapterId;

    public ChapterId() {
    }

    public ChapterId(String providerId, String locationId, String chapterId) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.chapterId = chapterId;
    }
   
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
    public String getChapterId() {
        return this.chapterId;
    }
    
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChapterId) ) return false;
		 ChapterId castOther = ( ChapterId ) other; 
         
		 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
 && ( (this.getChapterId()==castOther.getChapterId()) || ( this.getChapterId()!=null && castOther.getChapterId()!=null && this.getChapterId().equals(castOther.getChapterId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getChapterId() == null ? 0 : this.getChapterId().hashCode() );
         return result;
   }   


}


