package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * ComplianceCondition generated by hbm2java
 */
public class ComplianceCondition  implements java.io.Serializable {


     private ComplianceConditionId id;
     private String regulatedActivityId;
     private String complianceCondition;
     private String complianceReason;
     private String hashvalue;
     private Character action;

    public ComplianceCondition() {
    }

	
    public ComplianceCondition(ComplianceConditionId id, String regulatedActivityId) {
        this.id = id;
        this.regulatedActivityId = regulatedActivityId;
    }
    public ComplianceCondition(ComplianceConditionId id, String regulatedActivityId, String complianceCondition, String complianceReason, String hashvalue, Character action) {
       this.id = id;
       this.regulatedActivityId = regulatedActivityId;
       this.complianceCondition = complianceCondition;
       this.complianceReason = complianceReason;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public ComplianceConditionId getId() {
        return this.id;
    }
    
    public void setId(ComplianceConditionId id) {
        this.id = id;
    }
    public String getRegulatedActivityId() {
        return this.regulatedActivityId;
    }
    
    public void setRegulatedActivityId(String regulatedActivityId) {
        this.regulatedActivityId = regulatedActivityId;
    }
    public String getComplianceCondition() {
        return this.complianceCondition;
    }
    
    public void setComplianceCondition(String complianceCondition) {
        this.complianceCondition = complianceCondition;
    }
    public String getComplianceReason() {
        return this.complianceReason;
    }
    
    public void setComplianceReason(String complianceReason) {
        this.complianceReason = complianceReason;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


