package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * CqcAddressCache generated by hbm2java
 */
public class CqcAddressCache  implements java.io.Serializable {


     private Integer lid;
     private String street;
     private String additional;
     private String city;
     private String province;
     private String postalCode;
     private String country;
     private BigDecimal latitude;
     private BigDecimal longitude;

    public CqcAddressCache() {
    }

    public CqcAddressCache(String street, String additional, String city, String province, String postalCode, String country, BigDecimal latitude, BigDecimal longitude) {
       this.street = street;
       this.additional = additional;
       this.city = city;
       this.province = province;
       this.postalCode = postalCode;
       this.country = country;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(String additional) {
        this.additional = additional;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }




}


