package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * JudgementMethod generated by hbm2java
 */
public class JudgementMethod  implements java.io.Serializable {


     private JudgementMethodId id;
     private String methodText;
     private String hashvalue;
     private Character action;

    public JudgementMethod() {
    }

	
    public JudgementMethod(JudgementMethodId id) {
        this.id = id;
    }
    public JudgementMethod(JudgementMethodId id, String methodText, String hashvalue, Character action) {
       this.id = id;
       this.methodText = methodText;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public JudgementMethodId getId() {
        return this.id;
    }
    
    public void setId(JudgementMethodId id) {
        this.id = id;
    }
    public String getMethodText() {
        return this.methodText;
    }
    
    public void setMethodText(String methodText) {
        this.methodText = methodText;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


