package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * NominatedIndividual generated by hbm2java
 */
public class NominatedIndividual  implements java.io.Serializable {


     private NominatedIndividualId id;
     private String nominatedIndividual;
     private String hashvalue;
     private Character action;

    public NominatedIndividual() {
    }

	
    public NominatedIndividual(NominatedIndividualId id) {
        this.id = id;
    }
    public NominatedIndividual(NominatedIndividualId id, String nominatedIndividual, String hashvalue, Character action) {
       this.id = id;
       this.nominatedIndividual = nominatedIndividual;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public NominatedIndividualId getId() {
        return this.id;
    }
    
    public void setId(NominatedIndividualId id) {
        this.id = id;
    }
    public String getNominatedIndividual() {
        return this.nominatedIndividual;
    }
    
    public void setNominatedIndividual(String nominatedIndividual) {
        this.nominatedIndividual = nominatedIndividual;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


