package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * Outcome generated by hbm2java
 */
public class Outcome  implements java.io.Serializable {


     private OutcomeId id;
     private String judgementId;
     private String judgementDate;
     private String judgementReason;
     private String judgementUserExperience;
     private String judgementOtherEvidence;
     private String judgementScoreId;
     private String outcomeStatementId;
     private String judgementSummary;
     private String hashvalue;
     private Character action;

    public Outcome() {
    }

	
    public Outcome(OutcomeId id, String hashvalue) {
        this.id = id;
        this.hashvalue = hashvalue;
    }
    public Outcome(OutcomeId id, String judgementId, String judgementDate, String judgementReason, String judgementUserExperience, String judgementOtherEvidence, String judgementScoreId, String outcomeStatementId, String judgementSummary, String hashvalue, Character action) {
       this.id = id;
       this.judgementId = judgementId;
       this.judgementDate = judgementDate;
       this.judgementReason = judgementReason;
       this.judgementUserExperience = judgementUserExperience;
       this.judgementOtherEvidence = judgementOtherEvidence;
       this.judgementScoreId = judgementScoreId;
       this.outcomeStatementId = outcomeStatementId;
       this.judgementSummary = judgementSummary;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public OutcomeId getId() {
        return this.id;
    }
    
    public void setId(OutcomeId id) {
        this.id = id;
    }
    public String getJudgementId() {
        return this.judgementId;
    }
    
    public void setJudgementId(String judgementId) {
        this.judgementId = judgementId;
    }
    public String getJudgementDate() {
        return this.judgementDate;
    }
    
    public void setJudgementDate(String judgementDate) {
        this.judgementDate = judgementDate;
    }
    public String getJudgementReason() {
        return this.judgementReason;
    }
    
    public void setJudgementReason(String judgementReason) {
        this.judgementReason = judgementReason;
    }
    public String getJudgementUserExperience() {
        return this.judgementUserExperience;
    }
    
    public void setJudgementUserExperience(String judgementUserExperience) {
        this.judgementUserExperience = judgementUserExperience;
    }
    public String getJudgementOtherEvidence() {
        return this.judgementOtherEvidence;
    }
    
    public void setJudgementOtherEvidence(String judgementOtherEvidence) {
        this.judgementOtherEvidence = judgementOtherEvidence;
    }
    public String getJudgementScoreId() {
        return this.judgementScoreId;
    }
    
    public void setJudgementScoreId(String judgementScoreId) {
        this.judgementScoreId = judgementScoreId;
    }
    public String getOutcomeStatementId() {
        return this.outcomeStatementId;
    }
    
    public void setOutcomeStatementId(String outcomeStatementId) {
        this.outcomeStatementId = outcomeStatementId;
    }
    public String getJudgementSummary() {
        return this.judgementSummary;
    }
    
    public void setJudgementSummary(String judgementSummary) {
        this.judgementSummary = judgementSummary;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


