package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * Partner generated by hbm2java
 */
public class Partner  implements java.io.Serializable {


     private PartnerId id;
     private String partnerName;
     private String hashvalue;
     private Character action;

    public Partner() {
    }

	
    public Partner(PartnerId id) {
        this.id = id;
    }
    public Partner(PartnerId id, String partnerName, String hashvalue, Character action) {
       this.id = id;
       this.partnerName = partnerName;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public PartnerId getId() {
        return this.id;
    }
    
    public void setId(PartnerId id) {
        this.id = id;
    }
    public String getPartnerName() {
        return this.partnerName;
    }
    
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


