package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * RegisteredManagerId generated by hbm2java
 */
public class RegisteredManagerId  implements java.io.Serializable {


     private String providerId;
     private String locationId;
     private String regulatedActivityId;

    public RegisteredManagerId() {
    }

    public RegisteredManagerId(String providerId, String locationId, String regulatedActivityId) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.regulatedActivityId = regulatedActivityId;
    }
   
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
    public String getRegulatedActivityId() {
        return this.regulatedActivityId;
    }
    
    public void setRegulatedActivityId(String regulatedActivityId) {
        this.regulatedActivityId = regulatedActivityId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegisteredManagerId) ) return false;
		 RegisteredManagerId castOther = ( RegisteredManagerId ) other; 
         
		 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
 && ( (this.getRegulatedActivityId()==castOther.getRegulatedActivityId()) || ( this.getRegulatedActivityId()!=null && castOther.getRegulatedActivityId()!=null && this.getRegulatedActivityId().equals(castOther.getRegulatedActivityId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getRegulatedActivityId() == null ? 0 : this.getRegulatedActivityId().hashCode() );
         return result;
   }   


}


