package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * RegisteredManager generated by hbm2java
 */
public class RegisteredManager  implements java.io.Serializable {


     private RegisteredManagerId id;
     private String managerName;
     private String managerCondition;
     private String hashvalue;
     private Character action;

    public RegisteredManager() {
    }

	
    public RegisteredManager(RegisteredManagerId id) {
        this.id = id;
    }
    public RegisteredManager(RegisteredManagerId id, String managerName, String managerCondition, String hashvalue, Character action) {
       this.id = id;
       this.managerName = managerName;
       this.managerCondition = managerCondition;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public RegisteredManagerId getId() {
        return this.id;
    }
    
    public void setId(RegisteredManagerId id) {
        this.id = id;
    }
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }
    public String getManagerCondition() {
        return this.managerCondition;
    }
    
    public void setManagerCondition(String managerCondition) {
        this.managerCondition = managerCondition;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


