package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * RegulatedActivity generated by hbm2java
 */
public class RegulatedActivity  implements java.io.Serializable {


     private RegulatedActivityId id;
     private String hashvalue;
     private Character action;

    public RegulatedActivity() {
    }

	
    public RegulatedActivity(RegulatedActivityId id) {
        this.id = id;
    }
    public RegulatedActivity(RegulatedActivityId id, String hashvalue, Character action) {
       this.id = id;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public RegulatedActivityId getId() {
        return this.id;
    }
    
    public void setId(RegulatedActivityId id) {
        this.id = id;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


