package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * RoutineCondition generated by hbm2java
 */
public class RoutineCondition  implements java.io.Serializable {


     private RoutineConditionId id;
     private String regulatedActivityId;
     private String routineCondition;
     private String hashvalue;
     private Character action;

    public RoutineCondition() {
    }

	
    public RoutineCondition(RoutineConditionId id, String regulatedActivityId) {
        this.id = id;
        this.regulatedActivityId = regulatedActivityId;
    }
    public RoutineCondition(RoutineConditionId id, String regulatedActivityId, String routineCondition, String hashvalue, Character action) {
       this.id = id;
       this.regulatedActivityId = regulatedActivityId;
       this.routineCondition = routineCondition;
       this.hashvalue = hashvalue;
       this.action = action;
    }
   
    public RoutineConditionId getId() {
        return this.id;
    }
    
    public void setId(RoutineConditionId id) {
        this.id = id;
    }
    public String getRegulatedActivityId() {
        return this.regulatedActivityId;
    }
    
    public void setRegulatedActivityId(String regulatedActivityId) {
        this.regulatedActivityId = regulatedActivityId;
    }
    public String getRoutineCondition() {
        return this.routineCondition;
    }
    
    public void setRoutineCondition(String routineCondition) {
        this.routineCondition = routineCondition;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }




}


