package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * ServiceUserBand generated by hbm2java
 */
public class ServiceUserBand  implements java.io.Serializable {


     private ServiceUserBandId id;
     private String hashvalue;

    public ServiceUserBand() {
    }

	
    public ServiceUserBand(ServiceUserBandId id) {
        this.id = id;
    }
    public ServiceUserBand(ServiceUserBandId id, String hashvalue) {
       this.id = id;
       this.hashvalue = hashvalue;
    }
   
    public ServiceUserBandId getId() {
        return this.id;
    }
    
    public void setId(ServiceUserBandId id) {
        this.id = id;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }




}


