package org.cqc;
// Generated 23-May-2012 12:25:27 by Hibernate Tools 3.2.2.GA



/**
 * ServiceType generated by hbm2java
 */
public class ServiceType  implements java.io.Serializable {


     private ServiceTypeId id;
     private String hashvalue;

    public ServiceType() {
    }

	
    public ServiceType(ServiceTypeId id) {
        this.id = id;
    }
    public ServiceType(ServiceTypeId id, String hashvalue) {
       this.id = id;
       this.hashvalue = hashvalue;
    }
   
    public ServiceTypeId getId() {
        return this.id;
    }
    
    public void setId(ServiceTypeId id) {
        this.id = id;
    }
    public String getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }




}


