package org.cqc.etl.services.data;

import java.io.Serializable;
import org.cqc.etl.factories.pptest2.*;
import org.cqc.etl.model.obj.pptest2.Chapter;
import org.cqc.etl.model.obj.pptest2.ChapterPK;
import org.cqc.etl.model.obj.pptest2.Location;
import org.cqc.etl.model.obj.pptest2.LocationCondition;
import org.cqc.etl.model.obj.pptest2.LocationConditionPK;
import org.cqc.etl.model.obj.pptest2.LocationPK;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivity;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivityPK;
import org.cqc.etl.model.obj.pptest2.NominatedIndividual;
import org.cqc.etl.model.obj.pptest2.NominatedIndividualPK;
import org.cqc.etl.model.obj.pptest2.Outcome;
import org.cqc.etl.model.obj.pptest2.OutcomePK;
import org.cqc.etl.model.obj.pptest2.Partner;
import org.cqc.etl.model.obj.pptest2.PartnerPK;
import org.cqc.etl.model.obj.pptest2.Provider;
import org.cqc.etl.model.obj.pptest2.ProviderCondition;
import org.cqc.etl.model.obj.pptest2.ProviderConditionPK;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivity;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivityPK;
import org.cqc.etl.model.obj.pptest2.RegisteredManager;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerCondition;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerConditionPK;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerPK;
import org.cqc.etl.model.obj.pptest2.ReportSummary;
import org.cqc.etl.model.obj.pptest2.ReportSummaryPK;
import org.cqc.etl.model.obj.pptest2.ServiceType;
import org.cqc.etl.model.obj.pptest2.ServiceTypePK;
import org.cqc.etl.model.obj.pptest2.ServiceUserBand;
import org.cqc.etl.model.obj.pptest2.ServiceUserBandPK;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.ReplicationMode;
import org.hibernate.Session;
import java.util.Collection;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import com.felees.hbnpojogen.persistence.GenericDAO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.hibernate.LockMode;
import org.hibernate.SessionFactory;
import org.hibernate.proxy.HibernateProxy;
/** 
 * Data layer.
 * @author autogenerated
 */
@org.springframework.stereotype.Component
public class DataLayerPptest2Impl implements DataLayerPptest2 {
	/** Singleton reference to this class. */
	private static DataLayerPptest2 instance;
	/** map lock. */
	private static Object daoMapLock = new Object();

	/** Internal handle. */
	private static Map<Class<?>, GenericDAO<?, ?>> daoMap = null; 
	
		/** Inner handle. */
	private static ApplicationContext context;
 /** Sessionfactory in use. Filled in by Spring. */ 
    private SessionFactory sessionFactory = null;
	
	/** Handle to get back ourselves and perform correct injection. 
	 * @param ctxt filled by spring
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt) {
		DataLayerPptest2Impl.context = ctxt;
	}
	
	
		
 	/**
     * Set session factory.
     * @param sessionFactory sessionfactory to use. 
     */
    @Autowired
    public void setSessionFactory(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }
    
    /** 
	* Returns a DAO instance of the given type.
	* @param <T> Type
	* @param persistentObject to get
	* @return GenericDAO<T, ?> object
     */
    @SuppressWarnings("unchecked")
    private <T> GenericDAO<T, ?> getDAO(final T persistentObject) {
		T persistent = persistentObject;

		synchronized (daoMapLock) {
    		if (daoMap == null) {
    			daoMap = new ConcurrentHashMap<Class<?>, GenericDAO<?, ?>>(); 
	 	   		daoMap.put(Chapter.class, HibernatePptest2DaoFactory.getChapterDao());
	 	   		daoMap.put(Location.class, HibernatePptest2DaoFactory.getLocationDao());
	 	   		daoMap.put(LocationCondition.class, HibernatePptest2DaoFactory.getLocationConditionDao());
	 	   		daoMap.put(LocationRegulatedActivity.class, HibernatePptest2DaoFactory.getLocationRegulatedActivityDao());
	 	   		daoMap.put(NominatedIndividual.class, HibernatePptest2DaoFactory.getNominatedIndividualDao());
	 	   		daoMap.put(Outcome.class, HibernatePptest2DaoFactory.getOutcomeDao());
	 	   		daoMap.put(Partner.class, HibernatePptest2DaoFactory.getPartnerDao());
	 	   		daoMap.put(Provider.class, HibernatePptest2DaoFactory.getProviderDao());
	 	   		daoMap.put(ProviderCondition.class, HibernatePptest2DaoFactory.getProviderConditionDao());
	 	   		daoMap.put(ProviderRegulatedActivity.class, HibernatePptest2DaoFactory.getProviderRegulatedActivityDao());
	 	   		daoMap.put(RegisteredManager.class, HibernatePptest2DaoFactory.getRegisteredManagerDao());
	 	   		daoMap.put(RegisteredManagerCondition.class, HibernatePptest2DaoFactory.getRegisteredManagerConditionDao());
	 	   		daoMap.put(ReportSummary.class, HibernatePptest2DaoFactory.getReportSummaryDao());
	 	   		daoMap.put(ServiceType.class, HibernatePptest2DaoFactory.getServiceTypeDao());
	 	   		daoMap.put(ServiceUserBand.class, HibernatePptest2DaoFactory.getServiceUserBandDao());
    		}
		 }
		if (persistentObject instanceof HibernateProxy) {
			persistent = (T) ((HibernateProxy) persistentObject).getHibernateLazyInitializer().getImplementation();
		} 
		
		GenericDAO<T, ?> result = (GenericDAO<T, ?>) daoMap.get(persistent.getClass());
		if (result == null) {
			throw new IllegalAccessError("The given object is of an incorrect type. ");
		}
		return result;
    }

    /**
     * Deletes the given object from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to delete
     */
    public <T> void delete(T persistentObject) {
    	    	getDAO(persistentObject).delete(persistentObject);
    }
    /**
     * Refresh the object $class.className from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to reload
     */
    public <T> void refresh(T persistentObject) {
	    	getDAO(persistentObject).refresh(persistentObject);
    }

    /**
     * Saves the given object to disk.
     * @param persistentObject Object to save
	 * @param <T> A DataLayerObject-derived type
     * @return Identifier of saved object 
     */
    public <T> Serializable save(T persistentObject) {
        return getDAO(persistentObject).save(persistentObject);
    }
    /**
     * Saves or updates the given $class.className object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to save 
     */
    public <T> void saveOrUpdate(T persistentObject) {
        getDAO(persistentObject).saveOrUpdate(persistentObject);
    }
    /**
     * Updates the given object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to update 
     */
    public <T> void update(T persistentObject) {
        getDAO(persistentObject).update(persistentObject);
    }


    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Chapter obj) directly
     * @param id Identifier to delete
     */
    public void deleteChapter(final ChapterPK id)  {
        HibernatePptest2DaoFactory.getChapterDao().delete(loadChapter(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Chapter object
     */
    public Chapter loadChapter(final ChapterPK id) {
        return HibernatePptest2DaoFactory.getChapterDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Chapter getChapter(final ChapterPK id) {
        return HibernatePptest2DaoFactory.getChapterDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Location obj) directly
     * @param id Identifier to delete
     */
    public void deleteLocation(final LocationPK id)  {
        HibernatePptest2DaoFactory.getLocationDao().delete(loadLocation(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Location object
     */
    public Location loadLocation(final LocationPK id) {
        return HibernatePptest2DaoFactory.getLocationDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Location getLocation(final LocationPK id) {
        return HibernatePptest2DaoFactory.getLocationDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (LocationCondition obj) directly
     * @param id Identifier to delete
     */
    public void deleteLocationCondition(final LocationConditionPK id)  {
        HibernatePptest2DaoFactory.getLocationConditionDao().delete(loadLocationCondition(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a LocationCondition object
     */
    public LocationCondition loadLocationCondition(final LocationConditionPK id) {
        return HibernatePptest2DaoFactory.getLocationConditionDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public LocationCondition getLocationCondition(final LocationConditionPK id) {
        return HibernatePptest2DaoFactory.getLocationConditionDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (LocationRegulatedActivity obj) directly
     * @param id Identifier to delete
     */
    public void deleteLocationRegulatedActivity(final LocationRegulatedActivityPK id)  {
        HibernatePptest2DaoFactory.getLocationRegulatedActivityDao().delete(loadLocationRegulatedActivity(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a LocationRegulatedActivity object
     */
    public LocationRegulatedActivity loadLocationRegulatedActivity(final LocationRegulatedActivityPK id) {
        return HibernatePptest2DaoFactory.getLocationRegulatedActivityDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public LocationRegulatedActivity getLocationRegulatedActivity(final LocationRegulatedActivityPK id) {
        return HibernatePptest2DaoFactory.getLocationRegulatedActivityDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (NominatedIndividual obj) directly
     * @param id Identifier to delete
     */
    public void deleteNominatedIndividual(final NominatedIndividualPK id)  {
        HibernatePptest2DaoFactory.getNominatedIndividualDao().delete(loadNominatedIndividual(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a NominatedIndividual object
     */
    public NominatedIndividual loadNominatedIndividual(final NominatedIndividualPK id) {
        return HibernatePptest2DaoFactory.getNominatedIndividualDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public NominatedIndividual getNominatedIndividual(final NominatedIndividualPK id) {
        return HibernatePptest2DaoFactory.getNominatedIndividualDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Outcome obj) directly
     * @param id Identifier to delete
     */
    public void deleteOutcome(final OutcomePK id)  {
        HibernatePptest2DaoFactory.getOutcomeDao().delete(loadOutcome(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Outcome object
     */
    public Outcome loadOutcome(final OutcomePK id) {
        return HibernatePptest2DaoFactory.getOutcomeDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Outcome getOutcome(final OutcomePK id) {
        return HibernatePptest2DaoFactory.getOutcomeDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Partner obj) directly
     * @param id Identifier to delete
     */
    public void deletePartner(final PartnerPK id)  {
        HibernatePptest2DaoFactory.getPartnerDao().delete(loadPartner(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Partner object
     */
    public Partner loadPartner(final PartnerPK id) {
        return HibernatePptest2DaoFactory.getPartnerDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Partner getPartner(final PartnerPK id) {
        return HibernatePptest2DaoFactory.getPartnerDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Provider obj) directly
     * @param id Identifier to delete
     */
    public void deleteProvider(final String id)  {
        HibernatePptest2DaoFactory.getProviderDao().delete(loadProvider(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Provider object
     */
    public Provider loadProvider(final String id) {
        return HibernatePptest2DaoFactory.getProviderDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Provider getProvider(final String id) {
        return HibernatePptest2DaoFactory.getProviderDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ProviderCondition obj) directly
     * @param id Identifier to delete
     */
    public void deleteProviderCondition(final ProviderConditionPK id)  {
        HibernatePptest2DaoFactory.getProviderConditionDao().delete(loadProviderCondition(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ProviderCondition object
     */
    public ProviderCondition loadProviderCondition(final ProviderConditionPK id) {
        return HibernatePptest2DaoFactory.getProviderConditionDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public ProviderCondition getProviderCondition(final ProviderConditionPK id) {
        return HibernatePptest2DaoFactory.getProviderConditionDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ProviderRegulatedActivity obj) directly
     * @param id Identifier to delete
     */
    public void deleteProviderRegulatedActivity(final ProviderRegulatedActivityPK id)  {
        HibernatePptest2DaoFactory.getProviderRegulatedActivityDao().delete(loadProviderRegulatedActivity(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ProviderRegulatedActivity object
     */
    public ProviderRegulatedActivity loadProviderRegulatedActivity(final ProviderRegulatedActivityPK id) {
        return HibernatePptest2DaoFactory.getProviderRegulatedActivityDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public ProviderRegulatedActivity getProviderRegulatedActivity(final ProviderRegulatedActivityPK id) {
        return HibernatePptest2DaoFactory.getProviderRegulatedActivityDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (RegisteredManager obj) directly
     * @param id Identifier to delete
     */
    public void deleteRegisteredManager(final RegisteredManagerPK id)  {
        HibernatePptest2DaoFactory.getRegisteredManagerDao().delete(loadRegisteredManager(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a RegisteredManager object
     */
    public RegisteredManager loadRegisteredManager(final RegisteredManagerPK id) {
        return HibernatePptest2DaoFactory.getRegisteredManagerDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public RegisteredManager getRegisteredManager(final RegisteredManagerPK id) {
        return HibernatePptest2DaoFactory.getRegisteredManagerDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (RegisteredManagerCondition obj) directly
     * @param id Identifier to delete
     */
    public void deleteRegisteredManagerCondition(final RegisteredManagerConditionPK id)  {
        HibernatePptest2DaoFactory.getRegisteredManagerConditionDao().delete(loadRegisteredManagerCondition(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a RegisteredManagerCondition object
     */
    public RegisteredManagerCondition loadRegisteredManagerCondition(final RegisteredManagerConditionPK id) {
        return HibernatePptest2DaoFactory.getRegisteredManagerConditionDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public RegisteredManagerCondition getRegisteredManagerCondition(final RegisteredManagerConditionPK id) {
        return HibernatePptest2DaoFactory.getRegisteredManagerConditionDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ReportSummary obj) directly
     * @param id Identifier to delete
     */
    public void deleteReportSummary(final ReportSummaryPK id)  {
        HibernatePptest2DaoFactory.getReportSummaryDao().delete(loadReportSummary(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ReportSummary object
     */
    public ReportSummary loadReportSummary(final ReportSummaryPK id) {
        return HibernatePptest2DaoFactory.getReportSummaryDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public ReportSummary getReportSummary(final ReportSummaryPK id) {
        return HibernatePptest2DaoFactory.getReportSummaryDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ServiceType obj) directly
     * @param id Identifier to delete
     */
    public void deleteServiceType(final ServiceTypePK id)  {
        HibernatePptest2DaoFactory.getServiceTypeDao().delete(loadServiceType(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ServiceType object
     */
    public ServiceType loadServiceType(final ServiceTypePK id) {
        return HibernatePptest2DaoFactory.getServiceTypeDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public ServiceType getServiceType(final ServiceTypePK id) {
        return HibernatePptest2DaoFactory.getServiceTypeDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ServiceUserBand obj) directly
     * @param id Identifier to delete
     */
    public void deleteServiceUserBand(final ServiceUserBandPK id)  {
        HibernatePptest2DaoFactory.getServiceUserBandDao().delete(loadServiceUserBand(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ServiceUserBand object
     */
    public ServiceUserBand loadServiceUserBand(final ServiceUserBandPK id) {
        return HibernatePptest2DaoFactory.getServiceUserBandDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public ServiceUserBand getServiceUserBand(final ServiceUserBandPK id) {
        return HibernatePptest2DaoFactory.getServiceUserBandDao().get(id);
    }  
    /** Returns a singleton instance of this class.
     * @return an singleton instance
     */
    public static synchronized DataLayerPptest2 getInstance() {
        
        if (instance == null) {
        	if (context == null) {
        		throw new IllegalStateException("Context is null. Make sure Spring is initialized.");
        	}
     		instance = (DataLayerPptest2) context.getBean("dataLayerPptest2Impl");
        }
        
        return instance; 
    }
    /** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     public Query createQuery(final String query) {
        return this.sessionFactory.getCurrentSession().createQuery(query);
    }
    /** Returns a criteria handle.
     * @param criteria Criteria to use
     * @return A criteria instance
     */
     public Criteria createCriteria(final String criteria) {
        return this.sessionFactory.getCurrentSession().createCriteria(criteria);
    }
    /** Returns a Query handle based on your package-level named query.
     * @param query Query to use
     * @return A query instance
     */
     public Query getNamedQuery(final String query) {
        return this.sessionFactory.getCurrentSession().getNamedQuery(query);
    }
    /** Create a new Criteria instance, for the given entity class, or a superclass of an entity class.
	* @param persistentObject a class, which is persistent, or has persistent subclasses 
	* @return Criteria instance
	*/
	@SuppressWarnings("unchecked")
	public Criteria createCriteria(Class persistentObject) {
        return this.sessionFactory.getCurrentSession().createCriteria(persistentObject);
    }
    /** Flushes the currently open session.
	*/
	public void flushSession() {
        this.sessionFactory.getCurrentSession().flush();
    }
    /** Clears the currently open session.
	*/
	public void clearSession() {
        this.sessionFactory.getCurrentSession().clear();
    }
    /** Flushes and clears the currently open session.
	*/
	public void flushAndClearSession() {
		flushSession();
		clearSession();
    }
	/** Call currentSession.replicate.
	 * @param obj to replicate
	 * @param replicationMode mode
	 */ 
	public void replicate(Object obj, ReplicationMode replicationMode) {
		this.sessionFactory.getCurrentSession().replicate(obj, replicationMode);
	}
	/** Hibernate Merge. 
	 * @param obj to merge
	 * @return obj merged.
	 */
	public Object merge(Object obj) {
		return this.sessionFactory.getCurrentSession().merge(obj);
	}
	/** Returns the current session.
	 * @return the currently active session
	 */
	public Session getCurrentSession() {
		return this.sessionFactory.getCurrentSession();
	}
	/** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     public SQLQuery createSQLQuery(final String query) {
        return this.sessionFactory.getCurrentSession().createSQLQuery(query);
    }
    /** Remove this instance from the session cache. 
	 * Changes to the instance will not be synchronized with the database
	 * @param obj object to evict
	 */
	public void evict(Object obj) {
        this.sessionFactory.getCurrentSession().evict(obj);
    }
    /**
     * Return the persistent instance of the given entity class with the given 
     * identifier, or null if there is no such persistent instance. 
     * (If the instance, or a proxy for the instance, is already 
     * associated with the session, return that instance or proxy)
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return a persistent instance or null
     * @throws HibernateException
     */
	public Object get(Class<?> clazz, Serializable id) throws HibernateException {
        return this.sessionFactory.getCurrentSession().get(clazz, id);
    }	


    /**
     * Return the persistent instance of the given entity class with the given identifier, assuming that the instance exists.
     *You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return the persistent instance or proxy
     * @throws HibernateException
     */
	public Object load(Class<?> clazz, Serializable id) throws HibernateException {
        return this.sessionFactory.getCurrentSession().load(clazz, id);  
    }
	/**
	 * Reattaches the given entity to the current session using LockMode.NONE
	 *
	 * @param entity to reattach
	 */
	public void reattachEntityWithNoLock(IPojoGenEntity entity) {
		if (entity != null) {
        		this.sessionFactory.getCurrentSession().lock(entity, LockMode.NONE);
    		}
	}
	/**
	 * Reattaches the given entities to the current session.
	 *
	 * @param entities to attach
	 */
	public void reattachEntitiesWithNoLock(Collection<? extends IPojoGenEntity> entities) {
   		if (entities != null) {
		       for (IPojoGenEntity entity : entities) {
            		this.sessionFactory.getCurrentSession().lock(entity, LockMode.NONE);
        		 }
    		}
	}}

