package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ChapterPK;
import java.io.Serializable;
/**
 * DAO interface for table: ChapterPK.
 * @author autogenerated
 */
public interface ChapterPKDao extends GenericDAO<ChapterPK,  Serializable>  {
	// constructor only
}

