package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.Chapter;
import org.cqc.etl.model.obj.pptest2.ChapterPK;
/**
 * DAO interface for table: Chapter.
 * @author autogenerated
 */
public interface ChapterDao extends GenericDAO<Chapter,  ChapterPK>  {
	// constructor only
}

