package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.LocationPK;
import java.io.Serializable;
/**
 * DAO interface for table: LocationPK.
 * @author autogenerated
 */
public interface LocationPKDao extends GenericDAO<LocationPK,  Serializable>  {
	// constructor only
}

