package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.LocationCondition;
import org.cqc.etl.model.obj.pptest2.LocationConditionPK;
/**
 * DAO interface for table: LocationCondition.
 * @author autogenerated
 */
public interface LocationConditionDao extends GenericDAO<LocationCondition,  LocationConditionPK>  {
	// constructor only
}

