package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.LocationConditionPK;
import java.io.Serializable;
/**
 * DAO interface for table: LocationConditionPK.
 * @author autogenerated
 */
public interface LocationConditionPKDao extends GenericDAO<LocationConditionPK,  Serializable>  {
	// constructor only
}

