package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.Location;
import org.cqc.etl.model.obj.pptest2.LocationPK;
/**
 * DAO interface for table: Location.
 * @author autogenerated
 */
public interface LocationDao extends GenericDAO<Location,  LocationPK>  {
	// constructor only
}

