package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivityPK;
import java.io.Serializable;
/**
 * DAO interface for table: LocationRegulatedActivityPK.
 * @author autogenerated
 */
public interface LocationRegulatedActivityPKDao extends GenericDAO<LocationRegulatedActivityPK,  Serializable>  {
	// constructor only
}

