package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivity;
import org.cqc.etl.model.obj.pptest2.LocationRegulatedActivityPK;
/**
 * DAO interface for table: LocationRegulatedActivity.
 * @author autogenerated
 */
public interface LocationRegulatedActivityDao extends GenericDAO<LocationRegulatedActivity,  LocationRegulatedActivityPK>  {
	// constructor only
}

