package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.NominatedIndividual;
import org.cqc.etl.model.obj.pptest2.NominatedIndividualPK;
/**
 * DAO interface for table: NominatedIndividual.
 * @author autogenerated
 */
public interface NominatedIndividualDao extends GenericDAO<NominatedIndividual,  NominatedIndividualPK>  {
	// constructor only
}

