package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.NominatedIndividualPK;
import java.io.Serializable;
/**
 * DAO interface for table: NominatedIndividualPK.
 * @author autogenerated
 */
public interface NominatedIndividualPKDao extends GenericDAO<NominatedIndividualPK,  Serializable>  {
	// constructor only
}

