package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.Outcome;
import org.cqc.etl.model.obj.pptest2.OutcomePK;
/**
 * DAO interface for table: Outcome.
 * @author autogenerated
 */
public interface OutcomeDao extends GenericDAO<Outcome,  OutcomePK>  {
	// constructor only
}

