package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.OutcomePK;
import java.io.Serializable;
/**
 * DAO interface for table: OutcomePK.
 * @author autogenerated
 */
public interface OutcomePKDao extends GenericDAO<OutcomePK,  Serializable>  {
	// constructor only
}

