package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.PartnerPK;
import java.io.Serializable;
/**
 * DAO interface for table: PartnerPK.
 * @author autogenerated
 */
public interface PartnerPKDao extends GenericDAO<PartnerPK,  Serializable>  {
	// constructor only
}

