package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.Partner;
import org.cqc.etl.model.obj.pptest2.PartnerPK;
/**
 * DAO interface for table: Partner.
 * @author autogenerated
 */
public interface PartnerDao extends GenericDAO<Partner,  PartnerPK>  {
	// constructor only
}

