package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ProviderCondition;
import org.cqc.etl.model.obj.pptest2.ProviderConditionPK;
/**
 * DAO interface for table: ProviderCondition.
 * @author autogenerated
 */
public interface ProviderConditionDao extends GenericDAO<ProviderCondition,  ProviderConditionPK>  {
	// constructor only
}

