package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.Provider;
 
/**
 * DAO interface for table: Provider.
 * @author autogenerated
 */
public interface ProviderDao extends GenericDAO<Provider,  String>  {
	// constructor only
}

