package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivity;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivityPK;
/**
 * DAO interface for table: ProviderRegulatedActivity.
 * @author autogenerated
 */
public interface ProviderRegulatedActivityDao extends GenericDAO<ProviderRegulatedActivity,  ProviderRegulatedActivityPK>  {
	// constructor only
}

