package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ProviderConditionPK;
import java.io.Serializable;
/**
 * DAO interface for table: ProviderConditionPK.
 * @author autogenerated
 */
public interface ProviderConditionPKDao extends GenericDAO<ProviderConditionPK,  Serializable>  {
	// constructor only
}

