package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ProviderRegulatedActivityPK;
import java.io.Serializable;
/**
 * DAO interface for table: ProviderRegulatedActivityPK.
 * @author autogenerated
 */
public interface ProviderRegulatedActivityPKDao extends GenericDAO<ProviderRegulatedActivityPK,  Serializable>  {
	// constructor only
}

