package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerPK;
import java.io.Serializable;
/**
 * DAO interface for table: RegisteredManagerPK.
 * @author autogenerated
 */
public interface RegisteredManagerPKDao extends GenericDAO<RegisteredManagerPK,  Serializable>  {
	// constructor only
}

