package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerConditionPK;
import java.io.Serializable;
/**
 * DAO interface for table: RegisteredManagerConditionPK.
 * @author autogenerated
 */
public interface RegisteredManagerConditionPKDao extends GenericDAO<RegisteredManagerConditionPK,  Serializable>  {
	// constructor only
}

