package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerCondition;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerConditionPK;
/**
 * DAO interface for table: RegisteredManagerCondition.
 * @author autogenerated
 */
public interface RegisteredManagerConditionDao extends GenericDAO<RegisteredManagerCondition,  RegisteredManagerConditionPK>  {
	// constructor only
}

