package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.RegisteredManager;
import org.cqc.etl.model.obj.pptest2.RegisteredManagerPK;
/**
 * DAO interface for table: RegisteredManager.
 * @author autogenerated
 */
public interface RegisteredManagerDao extends GenericDAO<RegisteredManager,  RegisteredManagerPK>  {
	// constructor only
}

