package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ReportSummaryPK;
import java.io.Serializable;
/**
 * DAO interface for table: ReportSummaryPK.
 * @author autogenerated
 */
public interface ReportSummaryPKDao extends GenericDAO<ReportSummaryPK,  Serializable>  {
	// constructor only
}

