package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ReportSummary;
import org.cqc.etl.model.obj.pptest2.ReportSummaryPK;
/**
 * DAO interface for table: ReportSummary.
 * @author autogenerated
 */
public interface ReportSummaryDao extends GenericDAO<ReportSummary,  ReportSummaryPK>  {
	// constructor only
}

