package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ServiceUserBandPK;
import java.io.Serializable;
/**
 * DAO interface for table: ServiceUserBandPK.
 * @author autogenerated
 */
public interface ServiceUserBandPKDao extends GenericDAO<ServiceUserBandPK,  Serializable>  {
	// constructor only
}

