package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ServiceUserBand;
import org.cqc.etl.model.obj.pptest2.ServiceUserBandPK;
/**
 * DAO interface for table: ServiceUserBand.
 * @author autogenerated
 */
public interface ServiceUserBandDao extends GenericDAO<ServiceUserBand,  ServiceUserBandPK>  {
	// constructor only
}

