package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ServiceTypePK;
import java.io.Serializable;
/**
 * DAO interface for table: ServiceTypePK.
 * @author autogenerated
 */
public interface ServiceTypePKDao extends GenericDAO<ServiceTypePK,  Serializable>  {
	// constructor only
}

