package org.cqc.etl.model.dao.pptest2;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.cqc.etl.model.obj.pptest2.ServiceType;
import org.cqc.etl.model.obj.pptest2.ServiceTypePK;
/**
 * DAO interface for table: ServiceType.
 * @author autogenerated
 */
public interface ServiceTypeDao extends GenericDAO<ServiceType,  ServiceTypePK>  {
	// constructor only
}

